### ISSUE TITLE
请问你是用一个D435做3D重建的还是两个D435呢?

### ISSUE THREAD

**Issue by coldcoda** [AoLyu/capture_pointcloud_with_realsenseD435#1]
我也想做3D重建,是关于人脸的,但是不知道怎么处理?,我使用的是一个D435,之前尝试直接用PCL封装的ICP算法做,但是效果不好

**Comment by AoLyu** [comment]
> 我也想做3D重建,是关于人脸的,但是不知道怎么处理?,我使用的是一个D435,之前尝试直接用PCL封装的ICP算法做,但是效果不好
The single object was scaned by one camera,and the real-time registration of two point clouds  were scaned by two opposite cameras.I tried ICP berfore,it didn't work well when the overlapping area is small.So I designed these white key points,and match them myself.

**Comment by LiuTianyong** [comment]
请问你使用的open3d 版本是多少呢？

**Comment by AoLyu** [comment]
> 请问你使用的open3d 版本是多少呢？

it's 0.7.0

**Comment by LiuTianyong** [comment]
大佬可否留个联系方式，交流一下，不方便的话就算了

**Comment by AoLyu** [comment]
> 大佬可否留个联系方式，交流一下，不方便的话就算了

Sorry to reply you so late,I was busy with my graduation thesis last month.and I update this repo with o3d 0.8 . Maybe we can communicate with email(on my git homepage).
