### ISSUE TITLE
use mode

### ISSUE THREAD

**Issue by zuoligang1997** [AoLyu/capture_pointcloud_with_realsenseD435#2]
I am very interested to see your project, could you please provide the weight file of the network.
Thank you very much if you can.
Wish you a happy life!

**Comment by AoLyu** [comment]
Thanks for your interests, but sorry, I've graduated from school for 7 months. The weight files in the sever are now maintained by  my  junior fellow apprentice. However you can train your own models by simply following the DenseFusion‘s instructions. I just changed the number of objects and used the <https://github.com/thodan/bop_toolkit> to make my own dataset.
