### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by songjia** [AoLyu/capture_pointcloud_with_realsenseD435#4]
In **registration.py,** line 58: `if small_dis < 0.012:`

If the value of `small_dis` is not smaller than 0.012, `match_list` will remain empty.

Then line 64: `array1 = np.array(match_list)[:,0]` will have an IndexError.

I got this error when trying to use **interfaceVersion.py** for reconstruction.

**Comment by AoLyu** [comment]
@Songjia  Yes, you can change this value according to your own situation. I just used it to find the corresponding point pairs in two  point clouds
